import { createHash } from 'node:crypto';
import { dirname } from 'node:path';
import { describe, expect, it } from 'vitest';
import * as fc from 'fast-check';
import {
  deriveProjectId,
  ProjectMapRepository,
  serializeProjectMap
} from '../src/project-map.js';
import { ProjectMapError } from '../src/errors.js';
import type { DependencyPlacement, ProjectMap } from '../src/types.js';
import { createFakeFileSystem, propertyTag } from './fixtures/index.js';

interface SourceMetadata {
  readonly kind: 'registry' | 'directory' | 'git' | 'tarball';
  readonly locatorId: number;
  readonly version: number;
  readonly integrityId: number;
}

interface MapCase {
  readonly projectId: number;
  readonly unrelatedProjectId: number;
  readonly lockfileId: number;
  readonly generatedAtId: number;
  readonly sources: readonly SourceMetadata[];
}

const sourceMetadataArbitrary: fc.Arbitrary<SourceMetadata> = fc.record({
  kind: fc.constantFrom<SourceMetadata['kind']>('registry', 'directory', 'git', 'tarball'),
  locatorId: fc.integer({ min: 0, max: 999_999 }),
  version: fc.integer({ min: 0, max: 99 }),
  integrityId: fc.integer({ min: 0, max: 999_999 })
});

const mapCaseArbitrary: fc.Arbitrary<MapCase> = fc
  .record({
    projectId: fc.integer({ min: 0, max: 999_999 }),
    unrelatedProjectId: fc.integer({ min: 0, max: 999_999 }),
    lockfileId: fc.integer({ min: 0, max: 999_999 }),
    generatedAtId: fc.integer({ min: 0, max: 999_999 }),
    sources: fc.array(sourceMetadataArbitrary, { minLength: 1, maxLength: 6 })
  })
  .filter(({ projectId, unrelatedProjectId }) => projectId !== unrelatedProjectId);

describe('ProjectMapRepository property coverage', () => {
  it(propertyTag(6, 'Project maps are complete, collision-safe, and secret-free'), async () => {
    await fc.assert(
      fc.asyncProperty(mapCaseArbitrary, async (mapCase) => {
        const filesystem = createFakeFileSystem('/fixture');
        const projectRoot = `/fixture/projects/project-${mapCase.projectId}`;
        const unrelatedRoot = `/fixture/projects/unrelated-${mapCase.unrelatedProjectId}`;
        await filesystem.mkdir(projectRoot, { recursive: true });
        await filesystem.mkdir(unrelatedRoot, { recursive: true });

        const repository = new ProjectMapRepository({
          filesystem,
          projectsDir: '/fixture/store/projects'
        });
        const map = createMap(mapCase, `${projectRoot}/./`);
        const expectedId = deriveProjectId(projectRoot);

        // Occupy the shortest identifier with an unrelated root. This models
        // a project-root hash collision without relying on improbable SHA-256
        // collisions generated by the property test.
        const occupiedMap = createMap(mapCase, unrelatedRoot, expectedId);
        await filesystem.mkdir(dirname(repository.mapPath(expectedId)), { recursive: true });
        await filesystem.writeFileAtomic(repository.mapPath(expectedId), serializeProjectMap(occupiedMap));

        const published = await repository.publish(map);
        const republished = await repository.publish({ ...map, projectRoot });

        expect(published.projectId).not.toBe(expectedId);
        expect(republished.projectId).toBe(published.projectId);
        expect(published).toEqual({
          ...map,
          projectId: published.projectId,
          projectRoot
        });
        expect(await repository.read(published.projectId)).toEqual(published);
        expect(await repository.read(expectedId)).toEqual(occupiedMap);

        const raw = await filesystem.readTextFile(repository.mapPath(published.projectId));
        expect(JSON.parse(raw)).toEqual(published);
        expect(raw).not.toMatch(/registry\.example\.test|password|token|secret|authorization/i);

        const firstPlacement = published.placements[0];
        if (firstPlacement === undefined) throw new Error('Generated map must contain a placement.');
        const secretMap: ProjectMap = {
          ...published,
          placements: [{
            ...firstPlacement,
            peerContext: { authToken: 'do-not-persist' }
          }]
        };
        await expect(repository.publish(secretMap)).rejects.toBeInstanceOf(ProjectMapError);
        expect(await repository.read(published.projectId)).toEqual(published);
      }),
      { numRuns: 100 }
    );
  });
});

function createMap(mapCase: MapCase, projectRoot: string, projectId = 'caller-supplied-id'): ProjectMap {
  const placements = mapCase.sources.map((source, index) => createPlacement(mapCase, source, index));
  const lockfileHash = hash({ lockfileId: mapCase.lockfileId, sources: mapCase.sources });

  return {
    schemaVersion: 1,
    projectId,
    projectRoot,
    lockfileHash,
    placements,
    generatedAt: `2025-01-01T00:00:${String(mapCase.generatedAtId % 60).padStart(2, '0')}.000Z`,
    toolVersion: '0.1.0'
  };
}

function createPlacement(mapCase: MapCase, source: SourceMetadata, index: number): DependencyPlacement {
  const packageName = `@fixture/${source.kind}-${source.locatorId}-${index}`;
  const packageIdentityHash = hash({ source, index, projectId: mapCase.projectId });
  const placement: DependencyPlacement = {
    relativePath: `node_modules/${packageName}`,
    packageIdentityHash,
    packageName
  };

  if (index % 2 === 0) {
    return {
      ...placement,
      peerContext: { [`@fixture/peer-${index}`]: `1.${source.version}.0` },
      binEntries: { [`fixture-bin-${index}`]: 'bin/cli.js' }
    };
  }
  return placement;
}

function hash(value: unknown): string {
  return createHash('sha256').update(JSON.stringify(value), 'utf8').digest('hex');
}
